import { pgTable, varchar, numeric, timestamp, char } from 'drizzle-orm/pg-core';

// Define the synnex_flat_file table schema based on the DATABASE_REFERENCE.md
export const synnexFlatFile = pgTable('synnex_flat_file', {
  trading_partner_code: varchar('trading_partner_code'),
  detail_record_id: varchar('detail_record_id'),
  manufacturer_part_no: varchar('manufacturer_part_no'),
  td_synnex_internal_use: varchar('td_synnex_internal_use'),
  td_synnex_sku: numeric('td_synnex_sku'),
  status_code: char('status_code'),
  part_description: varchar('part_description'),
  manufacturer_name: varchar('manufacturer_name'),
  td_synnex_internal_use2: varchar('td_synnex_internal_use2'),
  qty_on_hand_total: numeric('qty_on_hand_total'),
  td_synnex_internal_use3: numeric('td_synnex_internal_use3'),
  td_synnex_internal_use4: numeric('td_synnex_internal_use4'),
  contract_price: numeric('contract_price'),
  msrp: numeric('msrp'),
  warehouse_qty_miami_fl: numeric('warehouse_qty_miami_fl'),
  warehouse_qty_tracy_ca_dartmouth_ns: numeric('warehouse_qty_tracy_ca_dartmouth_ns'),
  returnable_flag: char('returnable_flag'),
  warehouse_qty_reserved: numeric('warehouse_qty_reserved'),
  parcel_shippable: char('parcel_shippable'),
  warehouse_qty_calgary_alberta: numeric('warehouse_qty_calgary_alberta'),
  unit_cost: numeric('unit_cost'),
  warehouse_qty_romeoville_il_guelph_ontario: numeric('warehouse_qty_romeoville_il_guelph_ontario'),
  media_type: varchar('media_type'),
  warehouse_qty_southaven_ms: numeric('warehouse_qty_southaven_ms'),
  td_synnex_category_code: varchar('td_synnex_category_code'),
  warehouse_qty_reserved2: numeric('warehouse_qty_reserved2'),
  td_synnex_internal_use5: numeric('td_synnex_internal_use5'),
  ship_weight: numeric('ship_weight'),
  serialized_flag: char('serialized_flag'),
  warehouse_qty_columbus_oh: numeric('warehouse_qty_columbus_oh'),
  map_price: numeric('map_price'),
  coo_list: varchar('coo_list'),
  td_synnex_hc_price: numeric('td_synnex_hc_price'),
  upc_code: varchar('upc_code'),
  unspsc_code: varchar('unspsc_code'),
  td_synnex_internal_use6: varchar('td_synnex_internal_use6'),
  sku_created_date: varchar('sku_created_date'),
  sku_attributes: varchar('sku_attributes'),
  eta_date: varchar('eta_date'),
  abc_code: char('abc_code'),
  kit_stand_alone_flag: char('kit_stand_alone_flag'),
  state_gov_price: numeric('state_gov_price'),
  federal_gov_price: numeric('federal_gov_price'),
  educational_price: numeric('educational_price'),
  taa_flag: char('taa_flag'),
  gsa_pricing: numeric('gsa_pricing'),
  promotion_flag: char('promotion_flag'),
  promotion_comment: varchar('promotion_comment'),
  promotion_expiration_date: varchar('promotion_expiration_date'),
  long_description1: varchar('long_description1'),
  long_description2: varchar('long_description2'),
  long_description3: varchar('long_description3'),
  length: numeric('length'),
  width: numeric('width'),
  height: numeric('height'),
  warehouse_qty_suwanee_ga: numeric('warehouse_qty_suwanee_ga'),
  gsa_nte_price: numeric('gsa_nte_price'),
  platform_type: varchar('platform_type'),
  product_description_fr: varchar('product_description_fr'),
  product_street_date: varchar('product_street_date'),
  warehouse_qty_chino_ca_mississauga_ontario: numeric('warehouse_qty_chino_ca_mississauga_ontario'),
  warehouse_qty_swedesboro_nj_richmond_bc: numeric('warehouse_qty_swedesboro_nj_richmond_bc'),
  warehouse_qty_south_bend_in: numeric('warehouse_qty_south_bend_in'),
  warehouse_qty_fort_worth_tx: numeric('warehouse_qty_fort_worth_tx'),
  replacement_sku: varchar('replacement_sku'),
  minimum_order_qty: numeric('minimum_order_qty'),
  purchasing_requirements: varchar('purchasing_requirements'),
  gov_class: varchar('gov_class'),
  warehouse_qty_fontana_ca: numeric('warehouse_qty_fontana_ca'),
  mfg_drop_ship_warehouse_qty: numeric('mfg_drop_ship_warehouse_qty'),
  created_at: timestamp('created_at', { withTimezone: true }),
  updated_at: timestamp('updated_at', { withTimezone: true }),
});
